### ISSUE TITLE
riscv64: calloc() fails to handle overflow correctly

### ISSUE THREAD

**Issue by mateusz-bloch** [phoenix-rtos/phoenix-rtos-project#1008]
When calling `calloc()` with `SIZE_MAX` as both the number of elements and the size of each element, the function does not behave as expected. Instead of returning `NULL` and setting `errno` to `ENOMEM`, it behaves unexpectedly.

Reproduction:
```
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <errno.h>

int main() {
	errno = 0;
    int *ptr = calloc(SIZE_MAX, SIZE_MAX);
	printf("%d \n", ptr);
	printf("%d \n", errno);
    free(ptr);

    return 0;
}
```

Output RISCV64:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/116297248/b29c3db5-8528-4061-98b6-e17d4a2770c8)

Output IA32:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/116297248/e11b5fde-6a20-4403-8a2b-d8e6e1b7e62d)

**Comment by lukileczo** [comment]
Fixed yesterday, in https://github.com/phoenix-rtos/libphoenix/commit/4346c835dd6e7b6fd2baa71700983fa5eb255ac3
