### ISSUE TITLE
armv7m4-stm32l4x6: mkfifo fails to create fifo

### ISSUE THREAD

**Issue by mateusz-bloch** [phoenix-rtos/phoenix-rtos-project#1013]
`mkfifo` is not creating a named pipe on `stm32`

Code to reproduction:
```C
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <errno.h>

int main() {
    const char *fifoPath = "/tmp/my_fifo";

    if (mkfifo(fifoPath, S_IRUSR | S_IWUSR) == 0) {
        printf("FIFO '%s' created\n", fifoPath);
    } else {
        printf("mkfifo failed");
    }

    return 0;
}
```

**Comment by agkaminski** [comment]
Expected behavior, as named pipes require posixsrv

**Comment by gerard5** [comment]
I'm adding libposixsrv, maybe these PRs will solve the issue on stm32l4a6-nucleo evb:

- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/470
- https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1019
- https://github.com/phoenix-rtos/phoenix-rtos-build/pull/179

**Comment by mateusz-bloch** [comment]
Solved
