### ISSUE TITLE
tests:  certain binaries in tests using unity always return 0

### ISSUE THREAD

**Issue by mateusz-bloch** [phoenix-rtos/phoenix-rtos-project#1044]
The binary should return an exit code that equals the count of failed tests, allowing for proper error handling and reporting.

Example of the Issue:
```
int main(int argc, char *argv[])
{
	UnityMain(argc, (const char **)argv, runner);

	return 0;
}
```
 Solutions:
 Modify the main function to correctly reflect the outcome of UnityMain by returning its return value instead of a hardcoded 0.

**Comment by nalajcie** [comment]
IMHO we should just return `EXIT_SUCCESS` / `EXIT_FAILURE`.

Using exit status to return number of tests failed is unsafe (only  lowest 8 bits of exit status are accessible externally, values >127 are treated specially).
