### ISSUE TITLE
armv7m7-imxrt117x:  touch failure return EIO and VM pool exhaustion

### ISSUE THREAD

**Issue by mateusz-bloch** [phoenix-rtos/phoenix-rtos-project#1097]
Trying to enable [test execution in the new psh on this target](https://github.com/phoenix-rtos/phoenix-rtos-tests/actions/runs/9515528947/job/26230670331), in relation to the resolution provided in [issue #866](https://github.com/phoenix-rtos/phoenix-rtos-project/issues/866) . I encountered a failure when using `ls` in the test `touch`. The command `touch` returns success, but the `ls` print that the directory does not seem to exist when attempting to list it. Additionally, a error message `vm: Entry pool exhausted!` appears.

```
  (psh)% touch test_touch_dir/slash_file/
  (psh)% echo $?
  0
  (psh)% date +%Y:%m:%d:%H:%M:%S
  1970:01:01:00:00:03
  (psh)% ls -la test_touch_dir
  ls: can't access test_touch_dir: no such file or directory
  (psh)% exit
  (psh)% dmesg -E
  vm: Entry pool exhausted!
  (psh)% vm: Entry pool exhausted!
```
Currently, also with touch command in touch test:
```
  (psh)% mkdir /test_touch_dir/multi_arg9
  (psh)% echo $?
  0
  (psh)% touch /test_touch_dir/multi_arg9/K2C?i#8M /test_touch_dir/multi_arg9/+y?@ /test_touch_dir/multi_arg9/BUAX?
  psh: failed to touch /test_touch_dir/multi_arg9/+y?@: EIO
  psh: failed to touch /test_touch_dir/multi_arg9/BUAX?: EIO
  (psh)% exit
  (psh)% dmesg -E
  vm: Entry pool exhausted!
  vm: Entry pool exhausted!
  (psh)% vm: Entry pool exhausted!
  vm: Entry pool exhausted!
```

Problems occur after adding changes from :
```
* phoenix-rtos-kernel 7634e1e...5beec45 (3):
  > NOMMU: Implement message passing between processes of different MPU regions
  > imxrt: Fix hal_exceptionJump and initial stack align
  > armv7m: Enable MPU
```
Currently seeking an easy way to reproduce the issue with minimal code for a more straightforward investigation

**Comment by agkaminski** [comment]
I suspect that the pool has been exhausted indeed - it's size is based on the kernel's memory map (i.e. dtcm in this case). On this target we have many memory maps and these need entries too
