### ISSUE TITLE
libphoenix: `sscanf` may read past the end of input string

### ISSUE THREAD

**Issue by jmaksymowicz** [phoenix-rtos/phoenix-rtos-project#1116]
`sscanf` function using the `%c` format with specified width may read past the end of its input string if the input string is shorter than the width specified.
Code:
![bufferfail_code](https://github.com/user-attachments/assets/813689f7-6d5c-4ad7-9833-7689ddc8e4ac)
Expected output:
![bufferfail_good](https://github.com/user-attachments/assets/13c2aa6e-408d-4998-b67f-39fd2a246241)
`libphoenix` output:
![bufferfail_bad](https://github.com/user-attachments/assets/d6c529cd-1426-44fd-9579-654951b69782)

**Comment by Darchiv** [comment]
Fixed by https://github.com/phoenix-rtos/libphoenix/pull/370
