### ISSUE TITLE
docs: sphinx: elements of bullet list not printed when starting with `%`

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#1127]
https://docs.phoenix-rtos.com/utils/psh/psh-applets/top.html

![Screenshot from 2024-08-12 16-46-06](https://github.com/user-attachments/assets/0ef6473c-8896-4b09-922c-bd6e1ec91a08)

**Comment by adamdebek** [comment]
It just need to be escaped with `\`
