### ISSUE TITLE
armv8r52-mps3an536-qemu little kernel memory map

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#1171]
around 3GB of ddr memory is declared:
![image](https://github.com/user-attachments/assets/b9d5e1ed-0469-44d4-a6e2-2a78fc0e0a60)
But only 431KB is available:
![image](https://github.com/user-attachments/assets/b5da22ac-f43c-48e9-b278-483da0a11afd)

Due to this issue following psh tests fail: kill. mkdir, touch, exit

**Comment by mateusz-bloch** [comment]
Behavior on the current master is as follows when trying to run` armv8r52-mps3an536-qemu.sh`

```
Phoenix-RTOS loader v. 1.21 rev: 296a9d4
hal: Cortex-R52 MPS3-AN536
cmd: Executing pre-init script
console: Setting console to 0.2
Cannot allocate memory for 'phoenix-armv8r52-mps3an536.elf'
```

**Comment by agkaminski** [comment]
Seems to be working fine as of https://github.com/phoenix-rtos/phoenix-rtos-project/commit/bacc9cda61fb6d4be663c7fa781c5cbb7d108ce5

Original issue probably fixed in https://github.com/phoenix-rtos/phoenix-rtos-kernel/commit/74b869b07f93a8fc4dc8d81093f85a34677ecc6b

So I'm closing the issue
