### ISSUE TITLE
imxrt106x-evk: plo does not start after uploading via psu

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#1186]
The issue discovered after applying the following commit:
https://github.com/phoenix-rtos/plo/commit/ebd4d55a0edb77cd60752363cc4350ed39b68ee9

Reproduction:
1. Upload plo using psu to eval-kit
2. Assert that plo prompt starts and the plo device appears in dmesg output
 - From time to time (raughly 4/20 attempts) it will fail without any errors on dmesg and without any output on serial port
 
 For now tested on CI testing unit u1
 
 The error in CI looks as follows:
 
![Screenshot from 2024-10-01 13-04-40](https://github.com/user-attachments/assets/a2cf8053-fa78-4222-94d6-1c7960bf05da)

**Comment by jmaksymowicz** [comment]
Fixed by https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1193
