### ISSUE TITLE
imxrt117x: MemMgtFault on exit command

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#1194]
One of our previous target's on runner CI was `pimxrt1176` and this was experimental evk. After some time, we needed to replace it with normal `imxrt1176` (REV C1), because it has some problems not related to normal revision. After adjust runner to it, I found there is problem when `exit` command is executed.

Problem in runner:

![image](https://github.com/user-attachments/assets/1d599402-b770-4049-9ccf-1ded55191e47)

To reproduce this error simply, we need to flash imxrt1176, run new `psh` via `sysexec` and simply use `exit`.

Outcome :

![image](https://github.com/user-attachments/assets/d6984bd7-4ba2-4932-8e30-8b47d67e6796)

As we can see, runner don't report problem because it `exit` close `psh` but not in intentional way. This problem occurs on revision C1. In other hand on revision C3 there is no problem with this.

**Comment by damianloew** [comment]
I think to better show what is going on here we can change the name to `armv7m7-imxrt117x: MemMgtFault on exit command from newly spawned psh`

**Comment by agkaminski** [comment]
@maska989  This is a litmus paper of old toolchain :) On the current toolchain version this should not occur

**Comment by damianloew** [comment]
> @maska989 This is a litmus paper of the old toolchain :) On the current toolchain version this should not occur

It seems to be true, thanks for the quick reaction. Let's wait for @maska989 confirmation

**Comment by mateusz-bloch** [comment]
Everything works. Tested on the toolchain from the newest docker build image.
