### ISSUE TITLE
Inconsistent error handling for device files

### ISSUE THREAD

**Issue by mateusz-bloch** [phoenix-rtos/phoenix-rtos-project#1203]
I'm not sure if this is a bug or expected behavior, but it seems like certain devices are waiting for input and then failing. For example, when interacting with the `console`, it seems to expect input before failing. There is also a case with `ptmx` where it continuously accepts input without a clear exit.

```
(psh)% /dev/hda
psh: /dev/hda is not an executable
(psh)% /dev/console 
e
psh: /dev/console is not an executable
(psh)% /dev/ptmx

2
3
4
```

List of all of this devices:
```
"console", "ptmx", "ttyS0", "log", "uart1"
```

**Comment by damianloew** [comment]
As discussed during one of our meetings - we don't want to try executing devices, let's remove this runfile test case.
