### ISSUE TITLE
zynq7000-zedboard: logs from dummyfs duplicated during startup

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#1215]
![Screenshot from 2024-10-16 17-35-37](https://github.com/user-attachments/assets/bb1e40d8-15f3-44b1-b582-5e7f9efe0333)

- Also this one empty newline is not needed

For imxrt117x this log is not duplicated:
![Screenshot from 2024-10-16 17-27-03](https://github.com/user-attachments/assets/a16c346e-1b53-4e08-93c6-10c0104413e3)

**Comment by anglov** [comment]
There are two dummyfs on Zedboard - one for devfs, one for /tmp :)

**Comment by damianloew** [comment]
Oh, that's right - sorry for the mistake. Still, this newline is probably not necessary (?)

**Comment by nalajcie** [comment]
not our code (JFFS2 filesystem), we don't want to patch it unless absolutely necessary.
