### ISSUE TITLE
Clean up standard functions interface

### ISSUE THREAD

**Issue by Maxez** [phoenix-rtos/phoenix-rtos-project#129]
Phoenix-RTOS code base implements functions which slightly differ from their standard C library equivalents, e.g:
hal_memcpy() in phoenix-rtos-kernel/hal/ia32/string.h has following signature:
```c
void hal_memcpy(void *to, const void *from, unsigned int n);
```
whereas standard C memcpy():
```c
void *memcpy(void *to, const void *from, size_t n);
```
The standard functions could be changed to match those from the standard C library.
Some such changes were already introduced in plo ([link](https://github.com/phoenix-rtos/plo/pull/106)).

**Comment by nalajcie** [comment]
Fixed with https://github.com/phoenix-rtos/plo/pull/106
