### ISSUE TITLE
Error building for TARGET=ia32-generic

### ISSUE THREAD

**Issue by kemonats** [phoenix-rtos/phoenix-rtos-project#17]
Look:
- phoenix-rtos-kernel: [PR116](https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/116)
- phoenix-rtos-build: [PR19](https://github.com/phoenix-rtos/phoenix-rtos-build/pull/19)

**Comment by pawelpisarczyk** [comment]
Solved. Thx.
