### ISSUE TITLE
kernel: waitpid with WNOHANG option waits for a process state to change instead of returning value at once 

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#184]
The problem occurs when creating more than one processes in turn

Test, which reproduce issue: 

https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/49

**Comment by nalajcie** [comment]
Yep, I confirm that there is a problem with `waitpid` syscall implementation when `pid != -1` (any process) and there is at least one other pending zombie child. In that case:
 - `WNOHANG` option doesn't work
 - the `waitpid` turns into busy-waiting loop without any sleep inside taking as much CPU as it can

@damianloew with this information You could probably refine the testcase to trigger the error every time (spawn 2 childs - one which will exit soon, one which will never exit, sleep some time for the 1st one to become zombie process, use `waitpid` with `WNOHANG` to wait for the second process).

**Comment by damianloew** [comment]
Thanks, I updated test case

**Comment by agkaminski** [comment]
Fix here: https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/302

**Comment by agkaminski** [comment]
Fixed in 1cf2a6d86190ef1369f1b7ce471bb330cadb7452
