### ISSUE TITLE
Errors while building project for TARGET=ia32-generic

### ISSUE THREAD

**Issue by kemonats** [phoenix-rtos/phoenix-rtos-project#20]
- ### Building phoenix-rtos-devices
`phoenix-rtos-project/_build/ia32-generic/prog.stripped//pc-uart binary does not exist`
#### `build-core-ia32-generic.sh`: `pc-uart` instead `uart16550`
[PR26](https://github.com/phoenix-rtos/phoenix-rtos-build/pull/26)

- ### compiling `lighttpd`
```
checking for openssl/ssl.h... no
configure: error: openssl headers not found. install them or build without --with-openssl
```
#### `build.sh`: missing `-I${PREFIX_H}` in `CFLAGS`

or
[PR4](https://github.com/phoenix-rtos/phoenix-rtos-ports/pull/4)

**Comment by agkaminski** [comment]
Your PRs have been merged, thank you
