### ISSUE TITLE
plo: imxrt117x: usb cdc device driver doesn't run, when cpu frequency is 696 MHz

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#213]
The problem occurs once in a while when using 696 MHz cpu frequency. After setting serial downloader boot mode and running psu script there is no plo device available in /dev directory (also it isn't visible in dmesg output), so there is no way to run phoenixd properly.

To reproduce:

1. Set boot mode to serial download
2. Restart the board
3. Run `sudo ./psu plo-ram-armv7m7-imxrt117x.sdp`
4. Check if plo device is visible in dev directory: `ls -l /dev/serial/by-id` or check if last lines of `dmesg -w` command are equal to:  

![Screenshot from 2021-10-25 16-26-13](https://user-images.githubusercontent.com/77304431/138714278-73d00b92-b5bc-43ee-85a1-4f13da9f1942.png)

5. Repeat until the device doesn't appear (a few tries)

**Comment by gerard5** [comment]
I'm closing this problem because I have verified it on the particular device You tested and the problem no longer occurs (using `plo` with the fix mentioned above applied).
