### ISSUE TITLE
kernel: stm32l4x6: empty hal log

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#216]
![Screenshot from 2021-10-29 16-02-50](https://user-images.githubusercontent.com/77304431/139840264-c64c2201-c224-40f1-b719-4932eae99007.png)

![Screenshot from 2021-10-28 14-08-07](https://user-images.githubusercontent.com/77304431/139841771-f56c3800-50ac-47eb-9cf1-737c7ef4c05b.png)

The issue doesn't occur for ia32-generic and risc-v targets. I can't verify if in other hardware targets is the same problem.

Used target boards: NUCLEO-L4A6ZG, i.MX RT1064 EVK.

To reproduce the quickstarts can be useful:
https://github.com/phoenix-rtos/phoenix-rtos-doc/tree/master/quickstart

**Comment by agkaminski** [comment]
Fixed in [#phoenix-rtos-kernel f57d196e631021e2554aa819600d11b7c53ebed1](https://github.com/phoenix-rtos/phoenix-rtos-kernel/commit/f57d196e631021e2554aa819600d11b7c53ebed1)
