### ISSUE TITLE
stm32l4x6: psh prompt prints too early

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#226]
- The problem occurs once in a few times.
- Target board: NUCLEO-L4A6ZG
- 1 second sleep before starting psh helps
- Quiqstart can be helpful for reproduce: https://github.com/phoenix-rtos/phoenix-rtos-doc/blob/damianloew/rewrite_quickstart_chapter/quickstart/armv7m4-stm32l4x6.md

![Screenshot from 2021-11-09 12-21-53](https://user-images.githubusercontent.com/77304431/140915446-9d3bc77a-114c-440b-9c6d-e021ddefad97.png)

**Comment by agkaminski** [comment]
Should no longer occur after https://github.com/phoenix-rtos/phoenix-rtos-project/pull/471

**Comment by damianloew** [comment]
It seems to no longer occur
