### ISSUE TITLE
kernel: `proc_recv()` has unnecessary check for `-EINTR` error

### ISSUE THREAD

**Issue by niewim19** [phoenix-rtos/phoenix-rtos-project#246]
`proc_recv()` calls  for `proc_threadWaitInterruptible`:
```c
	while (p->kmessages == NULL && !p->closed && err != -EINTR)
		err = proc_threadWaitInterruptible(&p->threads, &p->spinlock, 0, &sc);
```
[permalink for code above](https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/ca42ff074069829b6841a9869761beb83d54404a/proc/msg.c#L379-L380)

Loop condition consists of checking for `-EINTR` but nowhere before can this value of `err` occur, and `proc_threadWaitInterruptible()` return value is based only on `hal_cpuReschedule()`, which after consulting with @HBuczynski can only return `EOK` or `-ETIME` error.

So checking  `err != -EINTR` in while loop seems unnecessary.

**Comment by agkaminski** [comment]
Sorry, I somewhat misled @HBuczynski - proc_threadWaitInterruptible is not protected against signals, so it can indeed return -EINTR
