### ISSUE TITLE
psh: vfork error, when using runfile applet with '/'

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#248]
Executing `/` returns vfork error:

![Screenshot from 2021-12-10 12-01-29](https://user-images.githubusercontent.com/77304431/145563923-51e3f329-f4fe-45db-a278-25091a65a624.png)

Tested on `ia32-generic qemu`.

**Comment by niewim19** [comment]
Two problems cause this strange behavior:
 - `psh` does not regain control over terminal if child process after `vfork()` terminates after `execve()` calls syscall `exec()`. This hangs the terminal (even though Phoenix-RTOS still works underneath) 
 - `execve()` and whole `exec()`s libphoenix functions do not check if they are trying to execute a directory and this results in _executing a directory_ which is deemed to fail but results in `EMOMEM` returned via `vfork()` error which gives wrong impression for user as what went wrong.

**Comment by niewim19** [comment]
All commits merged to repositories, this issue does not hang the system anymore. Issue will be closed after next submodules update.

**Comment by damianloew** [comment]
Fixed
