### ISSUE TITLE
psh: system crash after `touch` on binaries

### ISSUE THREAD

**Issue by niewim19** [phoenix-rtos/phoenix-rtos-project#252]
`touch /bin/psh` or `touch /bin/ls` commands results in system crash. Two screens below to replicate:
1)
![Screenshot from 2021-12-15 11-37-11](https://user-images.githubusercontent.com/80880689/146171241-4617af74-de9b-4acc-893d-dfd97be6377d.png)
2)
![Screenshot from 2021-12-15 11-36-39](https://user-images.githubusercontent.com/80880689/146171262-70bddf1b-f6e4-4202-bfc7-5260a634522d.png)
h

**Comment by niewim19** [comment]
Additionally this command completely erases files if they are present before command call.

This is due to use of `fopen()` function with option `"w"`. Libphoenix `open()` lacks support of `O_DIRECTORY` which is posix   -required so this needs bigger fix.

**Comment by niewim19** [comment]
- https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/112

Mentioned PR neutralizes `touch` command problems, and makes it _almost_ working if not for the lack of proper libphoenix/phoenix-rtos-kernel stubs and lack of implementations.

**Comment by damianloew** [comment]
Resolved
