### ISSUE TITLE
lwip: update source for contrib-lwip when available

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#266]
Temporarily, source for phoenix-rtos-lwip/contrib-lwip is https://github.com/damianloew/contrib-lwip/
When https://git.savannah.nongnu.org/git/lwip/lwip-contrib.git is available we will change it back.

**Comment by niewim19** [comment]
As of 21.12.21 the http://git.savannah.nongnu.org/ is accessible. 

After we decide if phoenix-rtos-lwip/contril-lwip is necessary for project integrity we will either rollback to savannah.org source or drop this submodule entirely.

**Comment by damianloew** [comment]
There is no contrib-lwip now.
