### ISSUE TITLE
kernel: `vm_pageinfo()` for nommu should signal lack of page structure

### ISSUE THREAD

**Issue by niewim19** [phoenix-rtos/phoenix-rtos-project#281]
Call to `vm_paeinfo()` on nommu target leaves `page` substructure in `_meminfo_t` structure undefined.

https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/4e89fbccfa73e749c7944841f4d4c802010c3e49/vm/page-nommu.c#L154-L164

This does not give information that data under `map` pointer is invalid.

**Comment by niewim19** [comment]
IMHO we can set `page.mapsz` to `-1` or `0` indicating that `map` pointer is invalid/undefined, and/or set `map` to `NULL`

**Comment by damianloew** [comment]
This issue causes reading undefined memory by `mem -p` psh command on non-mmu targets, for example `armv7m7-imxrt106x`:
![Screenshot from 2022-01-04 14-13-08](https://user-images.githubusercontent.com/77304431/148064347-43d408f3-6ba2-4128-893e-513b4fbfce6d.png)

**Comment by damianloew** [comment]
Fixed by https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/281 and https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/114
