### ISSUE TITLE
psh: mem: on no-mmu target (imxrt106x) the value of boot memory is printed as 0

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#284]
![Screenshot from 2022-01-07 16-43-23](https://user-images.githubusercontent.com/77304431/148568371-731d20fd-5568-43fe-b954-079a82b5d825.png)

**Comment by agkaminski** [comment]
By design - boot pages are pages reserved by bootloader that are within ranges used by kernel for memory allocation - there is none on this target.

**Comment by damianloew** [comment]
> By design - boot pages are pages reserved by bootloader that are within ranges used by kernel for memory allocation - there is none on this target.

Thanks, I wasn't sure about that.
