### ISSUE TITLE
Problem with docker-build.sh using clean all

### ISSUE THREAD

**Issue by kajaswat** [phoenix-rtos/phoenix-rtos-project#30]
tmpfs works fine when building without ports, eg:
`TARGET=ia32-generic ./docker-build.sh clean core fs project image`

when building with clean all, eg:
`TARGET=ia32-generic ./docker-build.sh clean all`

I got:
```
  Using /src/phoenix-rtos-ports/busybox/busybox-1.27.2/ as source for busybox
  GEN     /src/_build/ia32-generic/busybox/Makefile
  HOSTCC  scripts/basic/fixdep
/bin/sh: 1: scripts/basic/fixdep: Permission denied
make[2]: *** [scripts/Makefile.host:104: scripts/basic/fixdep] Error 126
make[1]: *** [/src/phoenix-rtos-ports/busybox/busybox-1.27.2//Makefile:357: scripts_basic] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [/src/phoenix-rtos-ports/busybox/busybox-1.27.2//Makefile:519: include/autoconf.h] Error 2
```

Skipping: 
`    TMPFS_OVERLAY=("--tmpfs"  "/src/_build")`
in docker-build.sh does the work but sets me back to 'painfully slow'.

**Comment by nalajcie** [comment]
I was able to reproduce the issue on linux. It turns out that `tmpfs` shares are mounted by default with `noexec` attribute which prevented to execute some host tool needed for `busybox` compilation.

Waiting for all the checks to pass before merging to master.
