### ISSUE TITLE
libphoenix/kernel: `lseek()` does not clear EOF flag

### ISSUE THREAD

**Issue by niewim19** [phoenix-rtos/phoenix-rtos-project#360]
# Test scenario
 - read all data from file using `read()` (`EOF` reached)
 - use `lseek()` with `SEEK_CUR` to get file offset back into valid file contents
 - try to read file contents again using `read()`

# Issue:
It is impossible to `read()` file contents even though `lseek()` returns proper values of file offset. Second `read()` will always return `0`, and no data is read.

Worth noting: **documentation does not specify whether `lseek()` shall clear EOF** flag if offset is brought back to valid position in file, as it is for `fseek()`. 

# Test case:
## Code:
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>

#define LINE1 "ABCD"

int main(void)
{
        char buf[50];
        int ret_lseek, ret_read;
        int fd = open("file", O_RDWR | O_CREAT | O_TRUNC);

        /* file preparation */
        write(fd, LINE1, sizeof(LINE1) - 1);
        lseek(fd, (off_t)0, SEEK_SET);

        /* TEST CASE */
        /* try to read more than there is in the file and clear buffer */
        read(fd, buf, 100);
        memset(buf, 0, sizeof(buf));
        /* lseek back into the valid file contents */
        ret_lseek = lseek(fd, -(sizeof(LINE1) - 1), SEEK_CUR);
        /* try to read back the contents of the file */
        ret_read = read(fd, buf, 10);
        /* print test checkout */
        printf("lseek returned: %d\nread returned: %d\nbuffer is: '%s'\n", ret_lseek, ret_read, buf);

        close(fd);
        return 0;
}
```
## Phoenix-RTOS output (ia32-generic):
```
lseek returned: 0
read returned: 0
buffer is: ''
```

## Linux output:
```
lseek returned: 0
read returned: 4
buffer is: 'ABCD'
```

**Comment by agkaminski** [comment]
@niewim19 
IMHO it's an error in the example code caused by linux on host having `sizeof(size_t) = 8`, but on phoenix it's 4.
Changing
`ret_lseek = lseek(fd, -(sizeof(LINE1) - 1), SEEK_CUR);`
to
`ret_lseek = lseek(fd, -(off_t)(sizeof(LINE1) - 1), SEEK_CUR);`

causes the code to work as intended.
