### ISSUE TITLE
Error while creating a project for riscv64-virt

### ISSUE THREAD

**Issue by kemonats** [phoenix-rtos/phoenix-rtos-project#39]
Openssl compilation error. Missing commit [8ef2d807fa761071bbb03dff936beac38c774f77](https://github.com/phoenix-rtos/phoenix-rtos-ports/commit/8ef2d807fa761071bbb03dff936beac38c774f77) in phoenix-rtos-ports.

commands:.
```
cd phoenix-rtos-project/
TARGET=riscv64-virt ./docker-build.sh clean all
```
message:
```
NOTE: If in doubt, on Unix-ish systems use './config'
```

**Comment by nalajcie** [comment]
Fixed via b9ecc81 (the same as #45)
