### ISSUE TITLE
libphoenix: `printf()` cannot print floats bigger than 2^20

### ISSUE THREAD

**Issue by niewim19** [phoenix-rtos/phoenix-rtos-project#400]
# Test scenario:
Printing floating point values larger than 2^20 results in wrong number printed (checked on ia32-generic)

# Test case:
Test code:
```c
	printf("%f\n", 1048575.F);   /* 2^20 - 1 */
	printf("%f\n", 1048576.F);   /* 2^20 */
	printf("%f\n\n", 1048577.F); /* 2^20 + 1 */

	printf("%f\n", 1048575.); /* 2^20 - 1 */
	printf("%f\n", 1048576.); /* 2^20 */
	printf("%f\n", 1048577.); /* 2^20 + 1 */
```
results in:
```
1048575.000000
1048576.000000
1099511627777.000000

1048575.000000
1048576.000000
1099511627777.000000
```

**Comment by niewim19** [comment]
Issue forces changes in tests proposed in 
 - https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/75

**Comment by gerard5** [comment]
Mention of pull-request which extends support for `%f` (float, doubles) -> https://github.com/phoenix-rtos/libphoenix/pull/228

**Comment by astalke** [comment]
Fixed in: 
- https://github.com/phoenix-rtos/libphoenix/pull/228
