### ISSUE TITLE
armv7a7-imx6ull-evk: can't communicate with psh

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#424]
For the latest commit in phoenix-rtos-project (d464da30ea18b1c79764fa841f91a23b261ea070). When uploading image to ram as required (https://github.com/phoenix-rtos/phoenix-rtos-doc/blob/master/quickstart/armv7a7-imx6ull.md) it seems like uart read does not work. There are no characters printed when entering them on the keyboard. Buliding with the following command: `TARGET=armv7a7-imx6ull-evk ./phoenix-rtos-build/build.sh clean core fs image project`
![Screenshot from 2022-06-13 11-20-21](https://user-images.githubusercontent.com/77304431/173323085-2e772f57-2a2b-4e20-a951-42ef08b07f3c.png)

**Comment by damianloew** [comment]
Probably the latest commit that works fine: de6a0627fcfd6d8229d557513e1ef7c9d7c0b9e1

**Comment by damianloew** [comment]
The commit in `phoenix-rtos-devices` that causes the issue: https://github.com/phoenix-rtos/phoenix-rtos-devices/commit/ba3a267df9f35a3161f4e4e2ca4e9990c198ebea

**Comment by damianloew** [comment]
It's the following change (not sure why it was applied):
![Screenshot from 2022-06-13 11-45-22](https://user-images.githubusercontent.com/77304431/173327402-4cf92354-ecb3-4bb8-941f-c631e9395017.png)

**Comment by nalajcie** [comment]
now RX doesn't work if the device isn't open (which is the correct behavior and saves some cpu clocks). Please verify if `psh` correctly opens the tty device file (maybe it's a problem with `psh` input params)

**Comment by damianloew** [comment]
After setting this macro console works, but very 'slowly
![Screenshot from 2022-06-21 16-27-45](https://user-images.githubusercontent.com/77304431/174825053-b831c365-1f02-4361-817c-44d3a877cda7.png)
'

**Comment by damianloew** [comment]
It seems to no longer occur, when using b64d8e617b5e68b6df4d6781a8ed1328a5ed1783 phoenix-rtos-project revision.
