### ISSUE TITLE
armv7a9-zynq7000-zedboard: `jffs2_do_read_inode_internal` warning

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#432]
When flashing the latest image (182030708e99818273f004ac4b0edbb9cbd072c8 - phoenix-rtos-project) the following warning appears:

![Screenshot from 2022-06-22 10-23-51](https://user-images.githubusercontent.com/77304431/174983933-695d13eb-3d3a-4702-a98c-6e918b32750f.png)

The sizes of built artifacts:

![Screenshot from 2022-06-22 10-23-06](https://user-images.githubusercontent.com/77304431/174985848-14d42cb3-9fce-4a30-9fd9-469864090786.png)

As @HBuczynski said, the partition size has to be increased to resolve it.

**Comment by HBuczynski** [comment]
The problem was related to wrong definition of fs partition offset.
Solved in : https://github.com/phoenix-rtos/phoenix-rtos-project/pull/474
