### ISSUE TITLE
ps does not show itself

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#446]
`ps` does not occur in the printed list of processes:
![Screenshot from 2022-07-06 12-25-38](https://user-images.githubusercontent.com/77304431/177530980-45e59ada-38a3-432b-a1a0-f539ce02f4b9.png)

I think, it could be done like this:
![Screenshot from 2022-07-06 12-33-19](https://user-images.githubusercontent.com/77304431/177531103-e6ca7fb8-73fa-45ad-a108-f929737a0459.png)

**Comment by agkaminski** [comment]
It shouldn't, as `ps` in `psh` does not spawn new process, it is executed within existing `psh`

**Comment by damianloew** [comment]
That's right, thanks
