### ISSUE TITLE
Error while bulding with docker

### ISSUE THREAD

**Issue by lTheMightyMl** [phoenix-rtos/phoenix-rtos-project#45]
Using
```TARGET=riscv64-spike ./docker_build.sh```
on macOS Big Sur results in
`/bin/sh: 5: riscv64-phoenix-elf-gcc-ranlib: not found`
`make: *** [Makefile:314: install_dev] Error 127`
I can't figure out what the problem is.

**Comment by nalajcie** [comment]
Hi,
for future: **please provide full command executed and output logs** - it would make diagnosing the problem much quicker.

I assume You tried to build `all` which is currently not supported for `riscv64-`  targets (no full POSIX support) and the building failed within `phoenix-rtos-ports` submodule.

Please try building with the command:
```bash
TARGET=riscv64-spike ./docker-build.sh clean core fs project image
```
If it still fails, feel free to reopen this issue :).

There is indeed configuration error within openssl compilation (invalid compiler name) which I will fix in a second.
