### ISSUE TITLE
`strto` functions don't set an `errno` in case of a failure 

### ISSUE THREAD

**Issue by PNieck** [phoenix-rtos/phoenix-rtos-project#543]
These functions:
- `strtod`
- `strtof`
- `strtoull`
- `strtoll`
don't set an `errno` is case of a failure

**Comment by gerard5** [comment]
Update: in this PR (https://github.com/phoenix-rtos/libphoenix/pull/233) I modified`strtoul()` and `strtol()` to set `errno`.

**Comment by gerard5** [comment]
Update: in this PR (https://github.com/phoenix-rtos/libphoenix/pull/233) I modified`strtoul()` and `strtol()` to set `errno`.

**Comment by Darchiv** [comment]
Resolved for `strtod()` and `strtof()` in https://github.com/phoenix-rtos/libphoenix/pull/193
Resolved for `strtoul()` and `strtol()` in https://github.com/phoenix-rtos/libphoenix/pull/233

Fix still needed for `strtoull()` and `strtoll()`
