### ISSUE TITLE
plo: new error after last changes: `Can't open file on usb0`

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#545]
- after the following changes in plo `can't open` error may occur in ~1/8 test runner campaigns. Even if it was not seen before, there could be an another reason.
    - 152a cmd: apply changes in interrupts API
    - bdc9 devices: apply changes in interrupts API
    - f6a0 hal/armv7m: allow to disable specific interrupt in NVIC
    - 7718 hal/ia32: apply changes in interrupts hal API
    - 0958 hal/armv7a: allow to disable specific interrupt in GIC
 
 - below is a test runner fail with output from phoenixd:
![Screenshot from 2022-11-04 16-53-01](https://user-images.githubusercontent.com/77304431/200311534-c9fd7209-d0d9-4591-80b5-20fd92cb0482.png)

 - after error plo seems to work properly (i. e. sending next commands)
 
 - caught when testing https://github.com/phoenix-rtos/phoenix-rtos-project/commit/1d61317bd06779bc2bcfb08f328f99f276842d76 phoenix-rtos-project with only plo changes (not caught when testing with commits to `a6df zynq7000-flash: add erase handler implementation`)

 - reproduced in 14th test runner campaign, when using the current phoenix-rtos-project revision: https://github.com/phoenix-rtos/phoenix-rtos-project/commit/dc5d14c4f82c7b766546967c4603385f6886f06f
 
![Screenshot from 2022-11-07 13-35-23](https://user-images.githubusercontent.com/77304431/200312008-f14093ea-c0bc-4621-8aa6-d5f8376a3579.png)

**Comment by agkaminski** [comment]
I don't really see anything dangerous in these commits, maybe it somehow made some other problem more apparent?

**Comment by damianloew** [comment]
I think so, please let me know what exactly can I check. Maybe it's related to https://github.com/phoenix-rtos/phoenix-rtos-project/issues/489

**Comment by agkaminski** [comment]
My thought for future debugging - it might be worth checking if `hal_interruptsDisable` really do disable interrupt

**Comment by damianloew** [comment]
It seemed to occur only on damaged imxrt117x-unit, so I think it's probably not a problem with system.

**Comment by damianloew** [comment]
As it was discovered during nightly run (https://github.com/phoenix-rtos/phoenix-rtos-project/actions/runs/5285224467/jobs/9563608911) this issue may still happen, even on a board without any fixes. This happen for the following phrtos-project revision: https://github.com/phoenix-rtos/phoenix-rtos-project/commit/ab93a3aeac748f002075fb997f1290f87b6bd19e

**Comment by damianloew** [comment]
Probably related with: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/710

**Comment by damianloew** [comment]
Update: the very similar issue is still being encountered, both on imxrt106x and imxrt117x. There are usually 2 following error messages:
![Screenshot from 2023-10-09 12-13-29](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/77304431/6538cd7c-03df-4821-b698-c7bf8dcae414)

![Screenshot from 2023-10-09 12-13-16](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/77304431/8e4706d7-c207-428f-ae7d-c6a07b23ec88)

There is nothing suspicious in dmesg output during those fails. It seems that phoenixd is launched too early and `0.5s` sleep after finding an ACM device in test runner solves the problem.

**Comment by damianloew** [comment]
Not seen anymore - probably fixed, I am closing it for now
