### ISSUE TITLE
switch to linking by gcc

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#587]
As mentioned there https://github.com/phoenix-rtos/phoenix-rtos-build/pull/136 changes like this won't be necessary then.

**Comment by badochov** [comment]
Isn't this one done? @nalajcie

**Comment by nalajcie** [comment]
Yep, done by https://github.com/phoenix-rtos/phoenix-rtos-build/commit/6ef56c5b3fd658de4b502c033c0fd834e112cac4
