### ISSUE TITLE
Error building the project.

### ISSUE THREAD

**Issue by kemonats** [phoenix-rtos/phoenix-rtos-project#6]
Run build.sh I get the error:

`sfdisk: command not found`

Cause:
Normal user does not have /usr/sbin and /sbin in the PATH variable

Solution:
e.g. add to file build.project

`PATH=$PATH:/usr/sbin:/sbin`

in the b_image() function

**Comment by Maxez** [comment]
Fixed by [8a9dd52](https://github.com/phoenix-rtos/phoenix-rtos-project/commit/8a9dd52eb8641186e06ce6d9b246fc665104aa5a)
