### ISSUE TITLE
Fscanf: Size_t length modifier problem

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#608]
- *All errors occur when length modifier %z** are used in *scanf on ia32-generic-qemu**
 - To reproduce issue copy following code:
```c
#include <stdio.h>

int main(void)
{
	
	char value[] ="123";
	size_t value_copy;
	static FILE *src;
	src = fopen("test","w+");
	fwrite(value,1,sizeof(value),src);
	fflush(src);
	rewind(src);
	fscanf(src,"%zd",&value_copy);
	printf("\nValue of fscanf when *zd with printf *ld used: %ld\n",value_copy);
	printf("\nValue of fscanf when *zd with printf *zd used: %zd\n",value_copy);
	fclose(src);

}
```
  - Tested on ia32-generic-qemu
![Screenshot from 2023-02-16 09-04-59](https://user-images.githubusercontent.com/49757239/219308001-1cb979fe-1ee9-4d3b-9768-704a965585bc.png)

**Comment by gerard5** [comment]
@maska989 I have added PR with solution that will close the issue, please verify on your side.

After applying the fix:
![2023-02-17-140609_608x193_scrot](https://user-images.githubusercontent.com/141153/219663238-22ae43d7-d18e-40ad-8a16-d1165d26cc85.png)
