### ISSUE TITLE
*Scanf and floating points related problems

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#609]
- **All errors occur when floating points value are used in **fscanf/sscanf/vfscanf/vsscanf** on ia32-generic-qemu**

 - To reproduce issue copy following code:
```c
#include <stdio.h>

int main(void)
{
	float val_f;
	float val_g;
	float val_G;
	float val_e;
	float val_E;
	float val_a;
	float val_A;

	float f = 123.123;
	char str_f[]= "123.123";
	sscanf(str_f,"%f",&val_f);
	sscanf(str_f,"%g",&val_g);
	sscanf(str_f,"%G",&val_G);
	sscanf(str_f,"%e",&val_e);
	sscanf(str_f,"%E",&val_E);
	sscanf(str_f,"%a",&val_a);
	sscanf(str_f,"%A",&val_A);

	printf("\n %f // %g // %G // %e // %E // %a // %A\n"
	,val_f, val_g, val_G, val_e, val_E, val_a, val_A);
}

```
  - Tested on ia32-generic-qemu
 
![Screenshot from 2023-02-17 15-31-33](https://user-images.githubusercontent.com/49757239/219682895-b4b1a851-b9b9-4533-90ce-3118333e5615.png)

It occure on : fscanf/sscanf/vfscanf/vsscanf funtions;

**Comment by gerard5** [comment]
That is not the case of `*scanf` (after applying my PR from the issue https://github.com/phoenix-rtos/phoenix-rtos-project/issues/604) which adds support for `%f` and other `aefgAEFG`, it scanfs the string correctly. Try changing printf (not supported `%` formats `aeAEG` into eg. `%f` or `%g` verify with for example like that that:
![2023-02-17-161212_536x124_scrot](https://user-images.githubusercontent.com/141153/219692288-d43d0203-ce76-452a-8f19-b1fb2c0924b8.png)

the output will be:
![2023-02-17-161317_749x110_scrot](https://user-images.githubusercontent.com/141153/219692541-9f2d3149-7649-4dca-91d9-f78680c1a28c.png)

**Comment by maska989** [comment]
@gerard5 Sorry again for bother. After your advice works fine. Thanks again.

**Comment by damianloew** [comment]
As mentioned above, the reason of this issue is wrong printf formatting, so it can be closed
