### ISSUE TITLE
ptrdiff_t length modifier for *scanf problem

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#617]
During scanf tests there was a problem reading data assigned as ptrdiff_t ("%t*") .

- In testing fallowing branch was used [https://github.com/phoenix-rtos/libphoenix/tree/astalke/RTOS-356](url) 

- To reproduce issue copy following code:
```c
#include <stdio.h>
#include <stddef.h>
#include <string.h>	
#include <limits.h>

#include <stdint.h>


int main(void)
{
	char str[125];

	sprintf(str,"%td",PTRDIFF_MAX);

 	ptrdiff_t val;
 	ptrdiff_t val1;
	
	printf("\n td = %s",str);

	sscanf(str,"%td",&val);
	printf("\nval with *td = %td",val);

	sscanf("2147483647","%td",&val1);
	printf("\nfinger val with *td = %td",val1);
	
	sscanf("2147483647","%ld",&val1);
	printf("\nfinger val with *ld = %ld",val1);
}
```

Outcome on Host-generic-pc  and ia32-generic-qemu:

![Screenshot from 2023-02-22 11-42-53](https://user-images.githubusercontent.com/49757239/220597260-c4b748d8-dd93-4eb5-89c4-18bc68df9c84.png)

**Comment by gerard5** [comment]
@maska989 the above pull-request should resolve this issue, please verify before merge:
![2023-02-23-001515_465x130_scrot](https://user-images.githubusercontent.com/141153/220785485-9ce7c2a4-9c2c-4df0-bc06-27a20c74b5a5.png)

**Comment by maska989** [comment]
@gerard5 After applying your pull-request everything works fine. Thanks.
