### ISSUE TITLE
tests/psh: `history` test code not amended after issue close

### ISSUE THREAD

**Issue by niewim19** [phoenix-rtos/phoenix-rtos-project#618]
In `tests/psh/history.py` there is a commented test with referenced issue. The issue is already solved and test case is still commented.

Testcase:
 - https://github.com/phoenix-rtos/phoenix-rtos-tests/blob/c68dd2fed4e468dfbcdcabe08059b3e1893b90c5/psh/test-history.py#L29-L32

Referenced issue:
 - https://github.com/phoenix-rtos/phoenix-rtos-project/issues/521

**Comment by damianloew** [comment]
Done
