### ISSUE TITLE
Functions `getline` and `getdelim` does not add terminating NUL, when end-of-file is encountered

### ISSUE THREAD

**Issue by PNieck** [phoenix-rtos/phoenix-rtos-project#628]
# Example

Suppose that we have such a file without new line character at the end of last line:
```
       ipsum
lorem
```

Then such a program:
```c
int main()
{
	char path[] = "path/to/file";

	FILE *file;
	char *line = NULL;
	size_t lineLen = 0;

	file = fopen(path, "r");
	if (file == NULL) {
		fprintf(stderr, "Error on file \"%s\" opening.\n", path);
		return;
	}

	while (getline(&line, &lineLen, file) != -1) {
		printf("%s", line);
	}

	fclose(file);
	free(line);
}
```

Gives such an output, which is different than file content:
```
       ipsum
lorem  ipsum
```

**Comment by PNieck** [comment]
Try without new line character after `lorem`

**Comment by gerard5** [comment]
@PNieck I added a quick-fix PR for that, please check if this solves the issue before merging.

**Comment by PNieck** [comment]
@gerard5 I have checked this PR and it seams to work
