### ISSUE TITLE
Scanf Inf and Nan handling problem

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#634]
### **During scanf tests there was a problem reading data assigned as INF and NAN**

The problem occurs in an all-conversion specifier wich can handle that (%aAeEgGfF).

There is posix requirements:

- Scanf documentation:
![Screenshot from 2023-03-07 11-31-47](https://user-images.githubusercontent.com/49757239/223424428-42d27c9d-f21a-4412-9a6a-551575067f60.png)

- Strtod documentation:
![Screenshot from 2023-03-07 11-31-16](https://user-images.githubusercontent.com/49757239/223424438-91ce6e46-ccf9-4b8b-81c0-d15514b720c0.png)
 - On reproducing this issue was used commit with sha number "bd57fdd3746e40dd60989277002ff949fcf0a348"
 - To reproduce issue copy following code:
``` c
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

int main(void)
{
	float val_float;

	sscanf("inf", "%f", &val_float);
	printf("\n%f\n", val_float);
	sscanf("infinity", "%f", &val_float);
	printf("\n%f\n", val_float);
	sscanf("InF", "%f", &val_float);
	printf("\n%f\n", val_float);
	sscanf("INFINITY", "%f", &val_float);
	printf("\n%f\n", val_float);
	sscanf("InFiNiTy", "%f", &val_float);
	printf("\n%f\n", val_float);

	sscanf("nan", "%f", &val_float);
	printf("\n%f\n", val_float);
	sscanf("NAn", "%f", &val_float);
	printf("\n%f\n", val_float);
	sscanf("NaN", "%f", &val_float);
	printf("\n%f\n", val_float);
	sscanf("nAN", "%f", &val_float);
	printf("\n%f\n", val_float);
	sscanf("nAn", "%f", &val_float);
	printf("\n%f\n", val_float);
}
```
 - Outcome on Host-generic-pc and ia32-generic-qemu:

![Screenshot from 2023-03-07 13-30-36](https://user-images.githubusercontent.com/49757239/223423957-63c4dba8-93ca-41a9-bbaa-4c6e25e430de.png)

**Comment by gerard5** [comment]
The `scanf(..)` implementation uses three functions `strtof()`, `strtod(..)`, `strtold(..)` to read and convert float/double/long double values. So the root problem is not in `scanf()` itself, but in the limited implementation of `strtold()` which is common base to the other two functions.

As I write in comment for https://github.com/phoenix-rtos/phoenix-rtos-project/issues/637#issuecomment-1460379655
