### ISSUE TITLE
Fscanf /vfscanf problem with setting file position indicator 

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#639]
* Using fscanf with specifier %c shall move the position indicator one place further but in this case, this function tries to pass over all characters in the file.

* Tested on Host-generic-pc and Ia32-generic-qemu.

* To reproduce issue copy following code:

``` c
#include <stdio.h>
int main(void)
{
	char c[1];
	FILE *rd;

	rd = fopen("test", "w+");

	fputs("abc", rd);

	fseek(rd, 0, SEEK_SET);
	printf("\nposi before = %ld\n", ftell(rd));

	fscanf(rd, "%c", c);
	printf("\nposi after = %ld\n", ftell(rd));

	fclose(rd);
}
```

* Outcome on Host-generic-pc and ia32-generic-qemu:
![Screenshot from 2023-03-10 11-13-53](https://user-images.githubusercontent.com/49757239/224291873-4f6734cc-e857-4f5b-bec2-5467d7587e26.png)

**Comment by gerard5** [comment]
@maska989 I added a fix, please verify if it works in your test cases.

**Comment by maska989** [comment]
@gerard5 Works like a charm.

**Comment by maska989** [comment]
https://github.com/phoenix-rtos/phoenix-rtos-tests/blob/c13ef424dff7c1f0f88f02e4a67104f6d9ed5d22/libc/stdio_scanf.c#L3330-L3333
