### ISSUE TITLE
Scanf doesn't support longer floating-point numbers

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#652]
**Problem occurs when floating-point numbers are used with high precision after coma**

Testesd between ia32-generic and host-generic

* Code to reproduction:

``` c
#include <stdio.h>
#include <stdlib.h>

int main(void)
{
	float f;
	sscanf("0.0000000000000000000000000000000011755", "%f", &f);
	printf("\n%.40f => 40 scanf", f);
	printf("\n%.40f => 40 strtof\n",
		strtof("0.0000000000000000000000000000000011755", NULL));
}
```

* Outcome: 
![Screenshot from 2023-03-13 12-46-18](https://user-images.githubusercontent.com/49757239/224693958-d4e36363-243c-42e6-8f68-8b68ab80d927.png)

But after further investigation, @niewim19 found a solution.
In scanf.c we need to change line 110
* From this:
![Screenshot from 2023-03-13 12-44-09](https://user-images.githubusercontent.com/49757239/224694812-a252e7e6-bd1a-46d2-b435-4986646cf920.png)

* To this (mine value to test):
![Screenshot from 2023-03-13 12-44-19](https://user-images.githubusercontent.com/49757239/224694894-5ecdab71-dc6c-4c32-a7e5-703d27c84ca9.png)

And outcome of what we got matched host-generic

![Screenshot from 2023-03-13 12-45-31](https://user-images.githubusercontent.com/49757239/224694977-1cf765fb-7011-4c29-8b0d-79fdb86643fa.png)

**Comment by niewim19** [comment]
Well... :) I have just found that we have a buffer of length 32 that is insufficient to hold the FLT_MIN (given it is 4 byte long) in decimal representation. This final buffer length should assessed as if we approach long double this buffer will bloat very much.

**Comment by gerard5** [comment]
Thanks @niewim19 for the tip. Of course, the buffer needs to be enlarged, but ***not at the expense of the stack*** (which is precious on small targets). Perhaps one solution might be to increase the `CCL` buffer which is already `malloc'ated` and share/use half of the space available for buffering purposes, another way might be to grow with `realloc` when it becomes necessary during format parsing. I'll try to figure it out and provide a fix.

**Comment by maska989** [comment]
https://github.com/phoenix-rtos/phoenix-rtos-tests/blob/c13ef424dff7c1f0f88f02e4a67104f6d9ed5d22/libc/stdio_scanf.c#L2641-L2647

**Comment by maska989** [comment]
https://github.com/phoenix-rtos/phoenix-rtos-tests/blob/c13ef424dff7c1f0f88f02e4a67104f6d9ed5d22/libc/stdio_scanf.c#L2641-L2647

**Comment by Darchiv** [comment]
Fixed by https://github.com/phoenix-rtos/libphoenix/pull/370
