### ISSUE TITLE
Missing float.h header file

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#656]
It could be very helpful to provide this POSIX header, especially for testing edge cases with floating point numbers.

**Comment by maska989** [comment]
https://github.com/phoenix-rtos/phoenix-rtos-tests/blob/c13ef424dff7c1f0f88f02e4a67104f6d9ed5d22/libc/stdio_scanf.c#L40

**Comment by agkaminski** [comment]
`float.h` is provided by gcc

**Comment by damianloew** [comment]
Yeah, @maska989 please try to use it as it's done in strto() functions tests. I think we can close this issue.
