### ISSUE TITLE
Scanf doesn't read 0x0 as null pointer

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#677]
* When using scanf to read 0x0 value on host-generic we get (nil), but on our system scanf does not recognize it as (nil).

 * Code to reproduce issue:
``` c
#include <stdio.h>

int main(void)
{
	void *ptr = (void *)0x1;

	printf("ret = %d\n", sscanf("(nil)", "%p", &ptr));
	printf("ptr = %p\n", ptr);
}
``` 

 * Output on ia32-generic-qemu and host-generic-qemu:
![Screenshot from 2023-03-30 16-31-56](https://user-images.githubusercontent.com/49757239/228870215-f8e4b6cd-674a-4f59-b9c0-22abea10693d.png)

**Comment by maska989** [comment]
https://github.com/phoenix-rtos/phoenix-rtos-tests/blob/c13ef424dff7c1f0f88f02e4a67104f6d9ed5d22/libc/stdio_scanf.c#L3548

**Comment by badochov** [comment]
@maska989 is the mentioned test reenabled?

**Comment by maska989** [comment]
> @maska989 is the mentioned test reenabled?

https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/265
There is PR, sorry for late update
