### ISSUE TITLE
This example project build for mx6ull or stm32 still not work

### ISSUE THREAD

**Issue by rqbh** [phoenix-rtos/phoenix-rtos-project#7]
I changed the build target in top fold file, both for mx6ull and stm32 not finish the build. 
but for ia-x86 work well

**Comment by nalajcie** [comment]
Right now the project builds successfully for all available targets. Moreover, it would be automatically checked by CI (see: https://github.com/phoenix-rtos/phoenix-rtos-project/actions?query=workflow%3Aci)
