### ISSUE TITLE
metaelf: elf.h is not possible to use on MacOS

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#701]
This header is not available on MacOS, even when libelf is provided. Temporary solution proposed in the following PR. To be considered what solution could be more suitable.

https://github.com/phoenix-rtos/phoenix-rtos-hostutils/pull/43

**Comment by gerard5** [comment]
It seems that `brew install libelf` and conditional `#include <libelf/libelf.h>` solve this issue, I'll prepare a patch with fix, and enable build of `metalf`. Also if not already in `.zshrc`, something a la `export C_INCLUDE_PATH=/usr/bin/local` is required, see the attached screenshot:

![2023-08-28-155554_1235x387_scrot](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/141153/cf336510-5bfa-4272-af4b-81b617dc4c18)
