### ISSUE TITLE
`strtod()`, `strtof()`, `strtold()` doesn't convert correctly `INFINITY` and `NAN`  value from string

### ISSUE THREAD

**Issue by mateusz-bloch** [phoenix-rtos/phoenix-rtos-project#704]
When the string to be converted by strtod(), strtof(), strtold() has a `INFINITY` or `NAN`  value, the conversion does not proceed correctly

- Code to reproduction:
```
#include <stdio.h>
#include <stdlib.h>

int main (void)
{
	const char *str[] = { "INFINITY", "-INFINITY", "NAN", "-NAN", "Inf", "-Inf", "NaN", "-NaN" };

	for (int i = 0; i < (sizeof(str) / sizeof(str[0])); i++) {
		printf("%lf\n", strtod(str[i], NULL));
		printf("%f\n", strtof(str[i], NULL));
		printf("%Lf\n", strtold(str[i], NULL));
		printf("\n");
	}
	
	return 0;
}
```
- Outcome from ia32-generic:
![image](https://user-images.githubusercontent.com/116297248/234255089-34fb1613-5a2b-4c32-b72f-25bf73ca0b38.png)

- Outcome from host-generic:
![image](https://user-images.githubusercontent.com/116297248/234255154-c5d85008-a799-49ba-91b4-dae532a0a88d.png)

**Comment by Darchiv** [comment]
Fixed by https://github.com/phoenix-rtos/libphoenix/pull/370
