### ISSUE TITLE
rand() lack of particular behaviour

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#708]
Posix stands:
If rand() is called before any calls to srand() are made, the same sequence shall be generated as when srand() is first called with a seed value of 1.
Sample code:
```C
#include <stdio.h>
#include <stdlib.h>

int main() {
    int i;
    int savdval[10];

    for (i = 0; i < 10; i++)
          savdval[i] = rand();
  
    for (i = 0; i < 10; i++)
          printf("%d ", savdval[i]);
    printf("\n");
  
    srand(1);
  
    for (i = 0; i < 10; i++)
          savdval[i] = rand();
  
    for (i = 0; i < 10; i++)
          printf("%d ", savdval[i]);
    printf("\n");

    return 0;
}
```
ia32-generic-qemu:
![image](https://user-images.githubusercontent.com/108683715/234541759-da37357d-ab71-401a-b743-0951e6f5c2d3.png)
host:
![image](https://user-images.githubusercontent.com/108683715/234543965-a07a9cd8-e1bd-465a-819c-23219f609e19.png)

**Comment by gerard5** [comment]
@adamdebek I've added a fix which solves this issue.
