### ISSUE TITLE
missing aio_write() POSIX function

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#711]
This missing POSIX function would be very helpful in https://github.com/phoenix-pilot/phoenix-pilot-project

**Comment by nalajcie** [comment]
I don't see a great advantage over writer thread or non-blocking IO with current architecture.

I think there is no plan to implement async IO operations in our OS in the foreseeable future.

**Comment by damianloew** [comment]
The approach with syslog may be an alternative solution on our system, aio functions are not planned to implement for now.
