### ISSUE TITLE
Zynq7000 Zedboard "Erase while flasing the device"

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#724]
A couple of weeks ago in the process of testing "on bench" we encountered a problem with Zynq 7000 Zedboard (Fresh units).
Even today on [GitHub-CI (direct link)](https://github.com/phoenix-rtos/plo/actions/runs/4937083017/jobs/8844355601) same problem appeared namely it is all about "ERROR WHILE FLASHING THE DEVICE".

This problem is hard to reproduce (it's showing up something like once on 50~60 runs) and sometimes is easier to get [other](https://github.com/phoenix-rtos/phoenix-rtos-project/issues/725) (maybe related to this) problem with jffs2.

Commit SHA used to reproduce: (commit c4c322a75b1333f4797fad184c313dd2feebee64)

![Screenshot from 2023-05-11 12-51-29](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/49757239/9fdb71ea-6cfa-4523-8161-a59ece2f4064)

 - What's going on in the screenshot:
   - On the left-upper corner we had our runner which encountered a problem with erase flash0 in the first case we were looking for a maybe bigger timeout on this in case zynq is likely to slow down, but that wasn't the solution.
   - On the right-upper corner we had `dmesg -w` running and it's looking like USB connected to Raspberry couldn't recognize zynq plo USB even if it had a couple of times it tries to reset the assigned.
   - On the left-down corner we tried to check if it was right what the dmesg says and what USB connection was missing.
   - On the right-down corner we used Picocom to connect to zynq to look inside what is going on and found out that Plo is up.

**Comment by badochov** [comment]
This issue haven't occured in a long time shall we close it?
@maska989 @agkaminski
