### ISSUE TITLE
Memcmp wrong char's interpretation

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#729]
While testing memcmp slight incompatibility with POSIX was found.

According to posix:
```
The memcmp() function shall compare the first n bytes (each interpreted as unsigned char) 
of the object pointed to by s1 to the first n bytes of the object pointed to by s2.

The sign of a non-zero return value shall be determined by the sign of the difference 
between the values of the first pair of bytes (both interpreted as type unsigned char) 
that differ in the objects being compared.
```

But in our system memcmp interpret these values as signed chars.

``` c
	if ((res = *((char *)s1++) - *((char *)s2++)))
		return res < 0 ? -1 : 1;
```
Permalink: https://github.com/phoenix-rtos/libphoenix/blob/b2a83353e473aa51a2b503a46c8c88a45c7a3871/string/string.c#L165-L174C7

**Comment by adamdebek** [comment]
Fixed in [adamdebek/RTOS-458](https://github.com/phoenix-rtos/libphoenix/tree/adamdebek/RTOS-458)
