### ISSUE TITLE
exit() doesn't flush buffored streams properly

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#734]
Code to reproduction:

```C
#include <stdio.h>
#include <stdlib.h>

#define PATH "/tmp/testFile"

int main()
{
        FILE *f = fopen(PATH, "w+");
	fprintf(f, "test123");
	exit(0);

        return 0;
}
```

ia32-generic-qemu output:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/7319359b-706c-4131-b44a-44177eb6a942)

host output:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/1c93f2bf-14ac-41f2-b4b8-ce24c049a34d)

**Comment by nalajcie** [comment]
turns out `fflush(NULL)` is incorrectly implemented in `libphoenix` (flushes only `stdout`, not all open output streams)
