### ISSUE TITLE
Riscv64 qemu/spike HAL Exception: 15 Store/AMO page fault

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#740]
HAL exception while trying to run Psh tests. First of all, I was thinking that I did something wrong but after little research got the same outcome on riscv64-generic-spike.

<details><summary>Commit SHA</summary>
<p>

[0fa9d55 <- project SHA](https://github.com/phoenix-rtos/phoenix-rtos-project/commit/0fa9d55561733aa7ba7933a367f9cbf245f63a00)

</p>
</details> 

Path to reproduce (qemu/spike): Build up an image with tests and lunch up emulator. After boot just run Psh tests using `./bin/psh` command

- **The output of emulator:**

![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/49757239/8406292c-b5ff-4a30-880b-3f9f1fa9b5b4)

**Comment by gerard5** [comment]
I've identified that these two (below) commits introduce the problem, if you reverse the changes below riscv64 works fine on master branch   [0494ae4](https://github.com/phoenix-rtos/phoenix-rtos-project/commit/0494ae4300dd195e84696732434e949cad87e6f8) , both `spike` and `qemu-system-riscv64`

* support for errno in thread local storage : https://github.com/phoenix-rtos/libphoenix/commit/079fa4447d26206aee88ea022753c6e28900a67c
* scheduler invoked indirectly via interrupts_dispatch (using threads_timeintr) : https://github.com/phoenix-rtos/phoenix-rtos-kernel/commit/87aca363a3da0f7bd4ffd59723a5fbd375626318

See https://github.com/phoenix-rtos/phoenix-rtos-doc/issues/152

**Comment by lukileczo** [comment]
This is problem with destruction of elf file, issue here https://github.com/phoenix-rtos/phoenix-rtos-project/issues/529

**Comment by agkaminski** [comment]
I disconnected https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/413 from this issue, as it needs further investigation, thanks @gerard5
