### ISSUE TITLE
imxrt106x strange behaviour (toolchain error??)

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#745]
Defining char array with more than 3 elements causes program to work improperly.
Defining char pointer with address of string literal works fine, defines don't cause problems neither.
Sample code which works:

```C
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>

#define PATH "testFile"
#define ABC "DASDASDASDASDASDASDAS"

int main(){
	int fd;
	char *nap = "dasdas";
	char abc1[] = "ab1";
	char abc2[] = "ab2";
	char abc3[] = "ab3";
	char abc4[] = "ab4";
	char abc5[] = "ab5";
	char abc6[] = "ab6";
	char abc7[] = "ab7";
	char abc8[] = "ab8";

    fd = open(PATH, O_RDWR | O_CREAT | O_TRUNC);
	if (fd < 0) {
		fprintf(stderr, "Couldn't open file\n");
		return 1;
	}

	printf("ret: %d\n" , write(fd, "123", 4));

	return 0;
}
```

Output:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/94b58417-7362-40bd-a13d-ad5255b98282)

However, when i change just abc8 with 1 more element, write returns -1;

```C
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>

#define PATH "testFile"
#define ABC "DASDASDASDASDASDASDAS"


int main(){
	int fd;
	char *nap = "dasdas";
	char abc1[] = "ab1";
	char abc2[] = "ab2";
	char abc3[] = "ab3";
	char abc4[] = "ab4";
	char abc5[] = "ab5";
	char abc6[] = "ab6";
	char abc7[] = "ab7";
	char abc8[] = "ab88"; //one more element

    fd = open(PATH, O_RDWR | O_CREAT | O_TRUNC);
	if (fd < 0) {
		fprintf(stderr, "Couldn't open file\n");
		return 1;
	}

	printf("ret: %d\n" , write(fd, "123", 4));

	return 0;
}
```
Output:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/bad2fb31-347e-430d-ae6e-5a0c5336f2e3)

**Comment by agkaminski** [comment]
What value of `errno` is after failed `write`?

**Comment by adamdebek** [comment]
22

**Comment by agkaminski** [comment]
There's a bug in the example - when passing `O_CREAT` to `open` you should include third argument - `mode`.

**Comment by agkaminski** [comment]
Should be `fd = open(PATH, O_RDWR | O_CREAT | O_TRUNC, S_IFREG);`
