### ISSUE TITLE
getdelim(): too large default buffer size for targets with MMU

### ISSUE THREAD

**Issue by kemonats** [phoenix-rtos/phoenix-rtos-project#753]
The default buffer size for targets with `MMU` in the `getdelim()` function set to 4096 bytes is probably to large.

https://github.com/phoenix-rtos/libphoenix/blob/a07e456a6a64e9958aec3d307fe9b5bf73617567/stdio/file.c#L915-L917
```c
        if (*lineptr == NULL || *n == 0) {
                *n = BUFSIZ;
                *lineptr = malloc(BUFSIZ);
```

https://github.com/phoenix-rtos/libphoenix/blob/a07e456a6a64e9958aec3d307fe9b5bf73617567/include/stdio.h#L31-L35
```c
#ifndef NOMMU
#define BUFSIZ _PAGE_SIZE
#else
#define BUFSIZ 80
#endif
```

```
include/arch/arm-imx/arch.h:36:#define _PAGE_SIZE 0x1000
include/arch/armv7/arch.h:36:#define _PAGE_SIZE 0x200
include/arch/ia32/arch.h:29:#define _PAGE_SIZE 0x1000
include/arch/riscv64/arch.h:29:#define _PAGE_SIZE 0x1000
include/arch/sparcv8leon3/arch.h:34:#define _PAGE_SIZE 0x200
```

**Comment by nalajcie** [comment]
IMHO it's probably not an issue and usually avoids `realloc` with `memcpy` - we usually do assume MMU platforms have plenty of RAM.

I've checked that:
- `newlib` starts with 128 bytes (https://github.com/bminor/newlib/blob/80ff7bc26ca97a7e2194554c21fe25cbdf227813/newlib/libc/stdio/getdelim.c#L40) 
- `glibc` starts with 120 (malloc overhead optimization? https://github.com/bminor/glibc/blob/d2fda60e7c4072180ba91df46bbbdacc0f4a133c/libio/iogetdelim.c#L64) 

We could probably downsize the buffer while exiting but I think it's not worth the hassle.

Leaving open for @agkaminski to decide.
