### ISSUE TITLE
busybox: Cannot use bzcat and gzip without -f on jffs2

### ISSUE THREAD

**Issue by mateusz-bloch** [phoenix-rtos/phoenix-rtos-project#762]
While operating with `bzcat` or `gzip` on `jffs2`, a prompt arises:` compressed data not read from terminal, use -f to force it`. This seems to cause the busybox/bzcat and busybox/gzip tests to fail. 

**Tested on armv7a9-zynq7000-qemu:**

Example of busybox tests:
`bzcat-does-not-remove-compressed-file`
```
echo foo | bzip2 >foo.bz2
busybox bzcat foo.bz2
test -f foo.bz2

```

`gzip-accepts-multiple-files`
```
touch foo bar
busybox gzip foo bar
test -f foo.gz -a -f bar.gz
```

**jffs2:**

- bzcat

![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/116297248/ceb4f2e4-8b4b-4db1-b066-9570d4d9b399)

- gzip

![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/116297248/e3c5cbf5-4dae-42e3-a0b9-e5c4fe6d1ed8)

**dummyfs:**

- bzcat

![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/116297248/c20759e3-afec-41d4-838f-82104a9a1027)

- gzip

![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/116297248/1984fff7-9961-47f2-9a07-3f84c1e92949)

**Comment by damianloew** [comment]
What do you mean with dummyfs?
