### ISSUE TITLE
Creating a project on TARGET=i386-generic doesn't work

### ISSUE THREAD

**Issue by kemonats** [phoenix-rtos/phoenix-rtos-project#8]
1. Incorrectly set BCC variable in file `plo/ia32/Makefile`.
2. No `ext2` filesystem support.
3. Empty partition table in the created image file.

I suggest adding to the `README.md` file information about the need to install the required packages:
``` libtool, genext2fs ```
required by plo:
``` bcc, as86, ld86 ```

**Comment by nalajcie** [comment]
Closing as obsolete - the target name was changed to `ia32-generic`. Docker build image contains all necessary tools and the image is built automatically by CI.

If You would have additional remarks regarding building HOWTO - please open separate PR in https://github.com/phoenix-rtos/phoenix-rtos-doc repository.
