### ISSUE TITLE
Lack of asynchronous I/O

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#807]
Asynchronous I/O is part of POSIX standard.

**Comment by nalajcie** [comment]
Please be more specific.

If I remember correctly, in POSIX:2008 it's not required (it is an extension) which was made part of the standard in later revisions.

Related to #711.

**Comment by damianloew** [comment]
Closed as we placed it in a list of POSIX incompliances on our Confluence (Continuous Integration -> Testing -> POSIX)

**Comment by agkaminski** [comment]
Suggestion: let's use "Close as not planned" in such cases
