### ISSUE TITLE
Ping: -i flag bottom limit doesn't work

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#851]
As the title says, ping command in psh doesn't have a bottom limit.

![Screenshot from 2023-09-25 14-22-20](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/49757239/84e0c52e-f4be-426a-83a1-9df72c073e49)

Code to reproduce (Run psh on imx6ull):
```
./etc/rc.d/network.sh
ping -i 0 -c 15 8.8.8.8
```
Output:

![Screenshot from 2023-09-25 14-26-28](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/49757239/5719f675-3c3d-4402-b07c-d0218162554b)

**Comment by nalajcie** [comment]
this limit is not needed, I think you can remove the info from help message and fix this issue by yourself :)
