### ISSUE TITLE
Latest riscv64-qemu hangs

### ISSUE THREAD

**Issue by KenDickey** [phoenix-rtos/phoenix-rtos-project#853]
The latest changes hang before %psh

[Phoenix-no-psh.txt](https://github.com/phoenix-rtos/phoenix-rtos-project/files/12717742/Phoenix-no-psh.txt)

**Comment by agkaminski** [comment]
According to git bisect https://github.com/phoenix-rtos/phoenix-rtos-kernel/commit/9c805e1024ac441aca124fb67c9575a3a2881bb2 is broken

**Comment by KenDickey** [comment]
psh verified working on riscv-qemu as of
 Phoenix-RTOS microkernel v. 3.0 rev: 10b2c6e
