### ISSUE TITLE
riscv64-qemu: kernel stack limit exceeded on GitHub Actions on GitHub hosted runners on psh/history test

### ISSUE THREAD

**Issue by mateusz-bloch** [phoenix-rtos/phoenix-rtos-project#859]
While testing `riscv64-generic-qemu` on CI, a kernel stack limit exceeded error appears. This issue did not occur during local testing.
It only appears in the `psh/history test`, even after changing SIZE_KSTACK in the kernel (https://github.com/phoenix-rtos/phoenix-rtos-kernel/commit/f9b1242f290b7cb6e470a54bf3aa432fae0e3a48).

Example:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/116297248/f7f1fc97-0830-4858-a52f-53690ed3674a)

**Comment by nalajcie** [comment]
I think it happens in the previous test - as a result of using `dmesg` command. 

Please compile locally with `DEBUG=1` (that's what enables stack canary checking in CI) and test it then.

**Comment by mateusz-bloch** [comment]
The issue is not present in the current revisions of the project
