### ISSUE TITLE
armv7m7-imxrt117x-evk: system occasionally freezes while exiting spawned psh

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#866]
- it occurs after executing some of psh tests (for example gibber, auth)
- discovered both on CI and locally
- phrtos-project rev: https://github.com/phoenix-rtos/phoenix-rtos-project/commits/master

![Screenshot from 2023-09-28 18-16-12](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/77304431/4a537830-3d30-4c02-a215-3f9857518003)

**Comment by damianloew** [comment]
On ea760a2fdc7ebb328303851bb29f086b3f4775c0 still occurs, but the behavior is a bit different:

```
(psh)% dmesg -D
(psh)% sysexec psh
(psh)% exit
(psh)% dmesg -E
(psh)% 
(psh)% ps
     PID     PPID PR STATE  %CPU    WAIT        TIME   VMEM THR CMD             
       0        0  4 ready  99.9   8.1ms    00:01:00  71.5K   2 [idle]
       1        0  4 sleep   0.0   705us    00:00:00      0   1 init
       2        1  4 sleep   0.0   519us    00:00:00  18.5K   1 dummyfs
       3        1  2 sleep   0.0   429us    00:00:00  20.5K  10 imxrt-multi
       4        1  4 ready   0.0   142us    00:00:00    31K   1 psh
(psh)% 
(psh)% dmesg -D
(psh)% sysexec psh
(psh)% exit
(psh)% dmesg -E
(psh)% 
(psh)% ps
     PID     PPID PR STATE  %CPU    WAIT        TIME   VMEM THR CMD             
       0        0  4 ready  99.9   8.1ms    00:01:19  71.5K   2 [idle]
       1        0  4 sleep   0.0   705us    00:00:00      0   1 init
       2        1  4 sleep   0.0   519us    00:00:00  18.5K   1 dummyfs
       3        1  2 sleep   0.0   429us    00:00:00  20.5K  10 imxrt-multi
       4        1  4 ready   0.0   142us    00:00:00    31K   1 psh
(psh)% 
(psh)% dmesg -D
```

As it is presented freeze happens while executing one of the next commands

**Comment by gerard5** [comment]
@damianloew  Have you tried with the [fix](https://github.com/phoenix-rtos/phoenix-rtos-build/commit/072b8599ebcf4178d0094d3ae256dd4e2eddba0c) in the toolchain build process that was recently merged?

**Comment by damianloew** [comment]
> @damianloew Have you tried with the [fix](https://github.com/phoenix-rtos/phoenix-rtos-build/commit/072b8599ebcf4178d0094d3ae256dd4e2eddba0c) in the toolchain build process that was recently merged?

Yeah, it was the reason why it was failing, with a newer toolchain the issue no longer occur, checked on ea760a2fdc7ebb328303851bb29f086b3f4775c0

Probably fixed in https://github.com/phoenix-rtos/phoenix-rtos-build/commit/072b8599ebcf4178d0094d3ae256dd4e2eddba0c (toolchain rebuild needed)

**Comment by nalajcie** [comment]
https://github.com/phoenix-rtos/phoenix-rtos-tests/blob/master/psh/tools/psh.py#L292 should be removed then
