### ISSUE TITLE
Kill() return wrong errno

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#870]
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/a49d1033-f9bd-416d-b6f2-c13af3543e22)

Reproduction:
```C
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>

int main(void)
{
	pid_t pid;

	pid = fork();
	/* child */
	if (pid == 0) {
		_exit(EXIT_SUCCESS);
	}
	/* parent */
	else {
		int status, ret;

		wait(&status);

		errno = 0;
		ret = kill(pid, SIGKILL);
		printf("ret: %d\n", ret);
		printf("errno: %d\n", errno);
	}
}
```
ia32-generic-qemu:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/33a2a6e2-5410-4ab0-aa60-49a9531e3438)

host:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/56950f18-bf25-47a7-840c-7dfe62fe5b22)

https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/51631c86f9bba2e4d9f6129f552662105cc29f31/posix/posix.c?plain=1#L2439-L2455

**Comment by damianloew** [comment]
@adamdebek could you enable test case related to this issue?
