### ISSUE TITLE
Atexit not calling function registed inside previously registered function

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#871]
From Open Group atexit() doc: _At normal program termination, all functions registered by the atexit() function shall be called, in the reverse order of their registration, except that a function is called after any previously registered functions that had already been called at the time it was registered._

Code to reproduction:
```C
#include <stdio.h>
#include <stdlib.h>

void f1(void) {
        printf("1111\n");
}

void f2(void) {
        printf("2222\n");
}

void f3(void) {
        atexit(f1);
        printf("3333\n");
}

int main(void)
{
        atexit(f1);
        atexit(f2);
        atexit(f3);

        return 0;
}
```

ia32-generic-qemu:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/736fcfbb-5de5-4b81-a064-a3e5a990bfcd)

host:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/13255718-edfa-4660-bac8-87b5305a4529)

**Comment by badochov** [comment]
@adamdebek I've added support for this, do we have some disabled tests that mey be reenabled?

**Comment by adamdebek** [comment]
I will enable it, these tests are still on my pr. Thanks for support addition.
