### ISSUE TITLE
armv7m4-stm32l4x6: usage fault/stuck when calling setsid in the child

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#885]
- Happens occasionally (caught during CI test campaigns)
 - Reproduction:
   - Checkout to the https://github.com/phoenix-rtos/phoenix-rtos-project/commit/07ee37d7c6a0641315a21cdb3111997d48f2617b phrtos project version
   - Edit the unistd_uids test file this way:
  ![Screenshot from 2023-10-11 11-25-05](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/77304431/a92445f1-8471-417d-bbc5-48a25e2e3ef4)
   - Run the libc-misc test on stm32l4x6-nucleo using test runner:
   ```
   ./runner.py -T armv7m4-stm32l4x6-nucleo -S -t libc
   ```
There will be stuck:
![Screenshot from 2023-10-11 11-34-46](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/77304431/cff34e77-1a31-418d-aaeb-ac014835c3b8)

or usage fault:
![Screenshot from 2023-10-11 11-23-14](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/77304431/9039ad0c-5bb6-45fa-a133-f89bdbeed695)

 - It may happen that the issue won't be caught, please run the test another time then.

 - The mentioned problem hasn't been discovered on the older project's revisions, like bbd9017c4b4bcffe203b82db8897ba53e38d1bc9. However, the specific commit, which is the source of this issue is hard to find. At the beginning of investigation reworking signals were supposed to be the cause, but after some time it was difficult to reproduce on 983716a375fc27f8eaa0e9986510e97ccdcb476f revision.

**Comment by agkaminski** [comment]
Thank you for a nice issue description and reproduction path

**Comment by mateusz-bloch** [comment]
Observed that the issue has popped up again., throwing a usage fault or a system hang. The problem appears to be related to the `vfork` function. It seems that the child process is exiting from `vfork`, while the parent process continues to perform operations on the child. Introducing a microsleep might suffice for a workaround. It is possible that a related problem may concern `fork`. 

![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/116297248/c17c80c3-c65c-4e86-b815-b654c39656b0)

**Comment by anglov** [comment]
Reproduction in text form:
```patch
diff --git a/libc/misc/unistd_uids.c b/libc/misc/unistd_uids.c
index f5e6f3c..ccc829d 100644
--- a/libc/misc/unistd_uids.c
+++ b/libc/misc/unistd_uids.c
@@ -184,8 +184,10 @@ TEST(unistd_uids, setpuids_setpgid)
 
 TEST_GROUP_RUNNER(unistd_uids)
 {
-       RUN_TEST_CASE(unistd_uids, getuids_parent);
-       RUN_TEST_CASE(unistd_uids, setuids_parent);
-       RUN_TEST_CASE(unistd_uids, setpuids_setsid);
-       RUN_TEST_CASE(unistd_uids, setpuids_setpgid)
+//     RUN_TEST_CASE(unistd_uids, getuids_parent);
+//     RUN_TEST_CASE(unistd_uids, setuids_parent);
+       for (int i = 0; i < 1000; i++) {
+               RUN_TEST_CASE(unistd_uids, setpuids_setsid);
+       }
+//     RUN_TEST_CASE(unistd_uids, setpuids_setpgid)
 }
```
