### ISSUE TITLE
zynq7000-qemu: errors that happen occasionally in test-exit

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#888]
![Screenshot from 2023-10-16 11-17-57](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/77304431/024fa96b-bb6b-477a-afa8-32d69c430408)
![Screenshot from 2023-10-16 11-19-01](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/77304431/6fef6ef9-c8cb-4a15-93fd-b4146bbdb7c8)

**Comment by badochov** [comment]
I've also seen some aborts on zedboard nightly runs, are they also appearing on this test only?

**Comment by damianloew** [comment]
> I've also seen some aborts on zedboard nightly runs, are they also appearing on this test only?

Yes, it may be related with the following error that you mentioned (from what I know it occurred only once):
![Screenshot from 2023-10-17 10-30-08](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/77304431/8143055e-c73c-43df-a70c-6fa115484bf8)

https://github.com/phoenix-rtos/phoenix-rtos-project/actions/runs/6367034681/job/17285380717

**Comment by badochov** [comment]
NOTE: I don't think those errors were present before around the time of signals rework.

**Comment by adamdebek** [comment]
This fixes the issue: https://github.com/phoenix-rtos/libphoenix/pull/303

**Comment by damianloew** [comment]
Moved to https://github.com/phoenix-rtos/phoenix-rtos-project/issues/891
Will be closed after closing the mentioned issue.
