### ISSUE TITLE
JFFS2: Newly created directory has wrong type, same with `.` and `..`

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#889]
Newly created directory has wrong type, same issue with `.` and `..` entries.
Code to reproduce:

```C
#include <stdio.h>
#include <dirent.h>
#include <sys/stat.h>
#include <string.h>

int main(void)
{
	int ret;
	DIR *dir;
	struct dirent *entry;

	ret = mkdir("testDir", S_IFDIR | 0775);
	if (ret < 0) {
		fprintf(stderr, "error in mkdir()\n");
	}

	ret = mkdir("testDir/inside", S_IFDIR | 0775);
	if (ret < 0) {
		fprintf(stderr, "error in mkdir()\n");
	}

	dir = opendir("testDir");
	if (dir == NULL) {
		fprintf(stderr, "error in opendir()\n");
	}
	
	while ( (entry = readdir(dir)) != NULL) {
		if (strcmp(entry->d_name, "inside") == 0) {
			break;
		}
	}
	
	printf("Current entry: %s\n", entry->d_name);

	if (entry->d_type == DT_DIR) {
		fprintf(stderr, "Success\n");
	}
	else {
		fprintf(stderr, "Fail\n");
	}

	rmdir("testDir/inside");
	rmdir("testDir");

	return 0;
}
```

host output:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/83a5660d-8572-4777-8be4-f611cc8783ef)

armv7a9-zynq7000-qemu output:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/e42dea8b-c616-414b-beff-a4bdc8d22d3f)

ia32-generic-qemu output:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/bdfa4f46-db4f-4ada-91c4-e04604fb90d3)

**Comment by adamdebek** [comment]
I updated reproducation code, but with `.`, `..` there is same output (armv7a9-zynq700-qemu):
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/e3c8896e-602d-492f-8760-1a080c2158fe)

**Comment by nalajcie** [comment]
ok, so probably `.` and `..` (internally created entries) do have incorrect type set - is the `inside` entry of the correct type?

If so, please update the issue title and description to reflect that.
