### ISSUE TITLE
_boot written as ELF instead of directory

### ISSUE THREAD

**Issue by michalnowowiejski** [phoenix-rtos/phoenix-rtos-project#9]
Building for targer armv7a7-imx6ull results in an error:
`=> Phoenix-RTOS kernel binary for [armv7a7-imx6ull] has been created`
`mkdir: cannot create directory ‘/home/michal/Projects/phoenix-rtos-project/_boot’: File exists`

The file _boot is created as a copy of a binary by line 57 in build-core-armv7a7-imx6ull.sh:
`cp "$PREFIX_BUILD_HOST/prog.stripped/phoenixd" "$PREFIX_BOOT"`
`cp "$PREFIX_BUILD_HOST/prog.stripped/psu" "$PREFIX_BOOT"`

**Comment by nalajcie** [comment]
fixed by https://github.com/phoenix-rtos/phoenix-rtos-build/commit/1e3f83a822ef79726e969d96c922ad7fd97a792c
