### ISSUE TITLE
Ftell() shows wrong position on files opened in "a+" and "ab+" mode

### ISSUE THREAD

**Issue by KArkadiusz** [phoenix-rtos/phoenix-rtos-project#924]
Checked on Phoenix-rtos-project commit 4e2ac6c.

Upon opening not empty file in "a+" and "ab+" modes, ftell() function shows that the pointer in the file lies at its end, like in "a" mode. Originally, the file pointer should be positioned at the beginning of the file. 

ia32 result:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/147424753/f50d175d-f01c-450f-b2fd-e5e1865521ae)

Host result:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/147424753/52e7b345-428a-4eb5-851d-0d61145d1331)

Code used for checking:

```
#include <stdio.h>

int main()
{
	FILE *f = fopen("test", "w+");
	fputs("1234wertgedr", f);
	fclose(f);

	f = fopen("test", "a+");
	printf("%ld\n", ftell(f));
	fclose(f);

	f = fopen("test", "a");
	printf("%ld\n", ftell(f));
	fclose(f);

	f = fopen("test", "ab+");
	printf("%ld\n", ftell(f));
	fclose(f);

	f = fopen("test", "ab");
	printf("%ld\n", ftell(f));
	fclose(f);

	remove("test");
	return 0;
}
```

I suspect it might be the fopen() problem, in test cases ftell() returned expected values in all modes except "a+" and "ab+" so it probably works fine.

**Comment by adamdebek** [comment]
Open Group does not directly specify position of file when opened in append mode, documentation only require subsequent
`write()` calls to that file to happen at the end-of-file. See: https://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html
