### ISSUE TITLE
Ext2 unresponsive during filling whole file system

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#927]
Output of fs_mark program:
Used revision: `7c9106a`
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/aad2cbe5-b90e-454d-b936-34546d4725b3)

It is easy to see that writing slows down with fs occupancy. When filled about 50-60% (in above case 55% and 2900 files of size 4096 bytes each) writing to fs loops indefinitely.

To reproduce build ia32-generic-qemu with ports (fs_mark) and run:
`/bin/fs_mark -d /fs_mark_test -s 4096 -w 1024 -n 100 -v -S 0 -F`

program argument synopsis:
-d - directory in which create filles
-s - size of each files
-w - size of single `write()` syscall
-n - number of files created in each loop
-v - verbose
-S 0 - no synchronization
-F - loop untill whole fs is filled

**Comment by jmaksymowicz** [comment]
I found two issues here:
* `ext2_block_create` sometimes returns `EOK` even though it didn't find any free blocks and sets the number of blocks found to 0. This causes an infinite loop in `ext2_block_sync`, which expects the function to find at least 1 block or return with an error code.
* `ext2_block_create` sometimes fails to find any free blocks even though there are free blocks on the disk. New files can be created through `cp` command without error, but the benchmark program no longer works. I'm still investigating the cause.
