### ISSUE TITLE
`Readdir()` with closed directory wrong behaviour

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#928]
Code to reproduction:
```
#include <dirent.h>
#include <errno.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/stat.h>

int main() {
	mkdir("a", 0700);
        DIR *d = opendir("a");
        closedir(d);

        errno = 0;
        printf("readdir: %p\n", readdir(d));

        printf("errno: %d\n", errno);
}
```

Output host:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/84299d2c-3556-4f45-8dfd-fd50af2ad560)
Output imx106 (dummyfs):
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/d6f96f72-deae-415f-829b-4e5e1b01126c)
Output zedboard (jffs2):
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/256cb109-5f63-42f1-8265-33425cf074a3)
Output ia32 (ext2):
Hangs ...
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/1acbd61d-a4a0-42c7-b82a-117522cc2916)

**Comment by nalajcie** [comment]
Specs for closedir says:  _Upon return, the value of dirp may no longer point to an accessible object of the type DIR_ (https://pubs.opengroup.org/onlinepubs/9699919799/functions/closedir.html)

There is no valid operation you can do on `d` after calling `closedir` (you essentially try to access free uninitialized memory) - It's within the specs for your program to abort, hang or perform in unexpected way.

What should not happen is for full OS to freeze or FS to break / became unavailable for other programs - please check if that is the case - if not, please close the issue.

**Comment by adamdebek** [comment]
I checked what you requested and it did not result in OS freeze or FS breakdown.
