### ISSUE TITLE
riscv64: error `long double` value declaration

### ISSUE THREAD

**Issue by mateusz-bloch** [phoenix-rtos/phoenix-rtos-project#988]
Encountered a problem on the riscv64 platform where declaring a variable as `long double` causes the compiled binary to exit with a return code of 132. 

Reproduction code:
```C
#include <stdio.h>

int main() {
    long double ld = 1.0;
    printf("Value: %Lf\n", ld);
    return 0;
}
```

Output for riscv64-qemu:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/116297248/13c105cd-cd6f-43ae-abca-3877c3243287)

Output for ia32-qemu:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/116297248/8f163d12-4e76-45de-858e-ddb027fe8563)

**Comment by lukileczo** [comment]
This is probably related to FPU currently being disabled on riscv64, while our compilation flags do not specify software FPU emulation. FPU handling on riscv64 is WIP (soon will be ready)
